import { 
  SiVuedotjs,
  SiReact,
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiTypescript,
  SiStyledcomponents,
  SiReactquery,
  SiWebpack,
  SiBabel,
  SiGraphql,
  SiVite,
  SiVitest,
  SiCypress,
  SiNx,
  SiDocker,
  SiGit,
  SiStorybook,
  SiJest,
  SiPuppeteer,
  SiPnpm,
  SiNodedotjs,
  SiYarn
} from 'react-icons/si';

import { FaAngular } from "react-icons/fa";

export const skillsList = [
  { name: "Angular", Icon: FaAngular },
  { name: "Vue.js", Icon: SiVuedotjs },
  { name: "React", Icon: SiReact },
  { name: "HTML5", Icon: SiHtml5 },
  { name: "CSS3", Icon: SiCss3 },
  { name: "JavaScript", Icon: SiJavascript },
  { name: "TypeScript", Icon: SiTypescript },
  { name: "Node.js", Icon: SiNodedotjs },
  { name: "Styled Components", Icon: SiStyledcomponents },
  { name: "React Query", Icon: SiReactquery },
  { name: "Webpack", Icon: SiWebpack },
  { name: "Babel", Icon: SiBabel },
  { name: "GraphQL", Icon: SiGraphql },
  { name: "Vite", Icon: SiVite },
  { name: "Vitest", Icon: SiVitest },
  { name: "Cypress", Icon: SiCypress },
  { name: "Nx", Icon: SiNx },
  { name: "Docker", Icon: SiDocker },
  { name: "Git", Icon: SiGit },
  { name: "Storybook", Icon: SiStorybook },
  { name: "Jest", Icon: SiJest },
  { name: "Puppeteer", Icon: SiPuppeteer },
  { name: "PNPM", Icon: SiPnpm },
  { name: "Yarn", Icon: SiYarn }
];